name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ma-muktadeer
          outputs: dist/snake.svg

      - name: Fix permissions for dist (ignore errors)
	run: chmod -R u+w dist || true

      - name: Add Gradient to Snake
        run: |
          sed -i 's/stroke="#.*"/stroke="url(#gradient)"/' dist/snake.svg
          sed -i '1i<defs><linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#ff6a00"/><stop offset="50%" stop-color="#ee0979"/><stop offset="100%" stop-color="#06beb6"/></linearGradient></defs>' dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}