name: Generate Gradient Snake

on:
  schedule:
    # প্রতিদিন রাত 12 টায় update হবে
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install d3 node-fetch

      - name: Generate Gradient Snake SVG
        run: node scripts/generate-gradient-snake.js

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update gradient snake"
          git push
