name: Generate Gradient Snake

on:
  schedule:
    # প্রতিদিন রাত 12 টায় update হবে
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ma-muktadeer
          outputs: |
            dist/snake.svg
          color_snake: "#ff6ec4"
          color_dots: "#ff6ec4 #7873f5 #06b6d4"  # gradient effect
          color_background: "transparent"
          speed: 2  # slow speed for smooth animation

      - name: Push snake animation to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git --work-tree=dist add --all
          git commit -m "Generate gradient snake"
          git push origin output --force
