name: Generate Snake Animation

# Workflow trigger
on:
  schedule:
    - cron: "0 */12 * * *"  # প্রতি 12 ঘন্টায় auto run
  workflow_dispatch:          # Manual run option
  push:
    branches:
      - main

# Permissions fix
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake with custom color
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ma-muktadeer
          outputs: |
            dist/snake.svg
          # Customization
          color_snake: "#3B82F6"          # Tail color (blue-500)
          color_dots: "#FACC15 #22C55E"   # Dots gradient (yellow-green)
          color_background: "transparent" # Background transparent

      # Push snake.svg to output branch
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
